defaults:
  - data_stream: flow
  - model: i3d 
  - model_type: ${defaults.1.model}_${defaults.0.data_stream}
  - transforms: ${defaults.0.data_stream}
  - augmentations: ${defaults.0.data_stream}
  - data: base
  - data_set: 2c

logging:
  logging_enabled: True
  project_name: 'eiphodos/SUEF'
  experiment_name: 'i3d'

performance:
  cuddn_auto_tuner: True
  amp_enabled: True
  amp_opt_level: O2
  parallel_mode: False
  anomaly_detection: False
  gradient_clipping: True
  gradient_clipping_max_norm: 32752

data_loader:
  batch_size: 16
  n_workers: 11
  custom_collate: False
  drop_last: True
  shuffle: True

optimizer:
  learning_rate: 0.01
  weight_decay: 0.00001

training:
  epochs: 50
  use_scheduler: True
  sched_step_size: 15
  sched_gamma: 0.1
  checkpointing_enabled: True
  checkpoint_save_path: /home/ola/Projects/SUEF/saved_models/
  freeze_lower: False
