defaults:
  - data_type: multistream
  - model: i3d_bert
  - model_type: ${defaults.1.model}_${defaults.0.data_type}
  - transforms: ${defaults.0.data_type}
  - augmentations: ${defaults.0.data_type}
  - data_set: 8stream

data:
  data_in_mem: False
  only_use_complete_exams: False
  preprocessed_data_on_disk: True
  temp_folder_img: /proj/suef_data/temp/img
  temp_folder_flow: /proj/suef_data/temp/flow
  file_sep: ;
  base_target_folder: /proj/suef_data/targets
  data_folder: ${data.base_data_folder}/${data.type}/
  train_targets: ${data.base_target_folder}/train_new_views_merged.csv
  val_targets: ${data.base_target_folder}/val_new_views_merged.csv
  test_targets: ${data.base_target_folder}/test_new_views_merged.csv

logging:
  logging_enabled: True
  project_name: 'jenniferalven/lvef'
  experiment_name: ${model.name}

performance:
  device: cuda
  ddp: True
  cuddn_auto_tuner: True
  parallel_mode: True
  half_precision: True
  anomaly_detection: False
  gradient_clipping: True
  gradient_clipping_max_norm: 1

data_loader:
  batch_size_train: 16
  batch_size_eval: 16
  n_workers: 20
  custom_collate: False
  drop_last: True
  weighted_sampler: True

optimizer:
  loss_function: mse
  loss_epsilon: 1
  learning_rate: 0.001
  weight_decay: 0.0001
  use_scheduler: True
  s_patience: 3
  s_factor: 0.1

training:
  epochs: 500
  checkpointing_enabled: True
  continue_training: True
  checkpoint_save_path: /proj/suef_data/saved_models/
  freeze_lower: False

evaluation:
  use_best_sample: True
