defaults:
  - data_type: flow
  - model: i3d_bert
  - model_type: ${defaults.1.model}_${defaults.0.data_type}
  - transforms: ${defaults.0.data_type}
  - augmentations: ${defaults.0.data_type}
  - data_set: 3c

data:
  data_in_mem: True
  file_sep: ;
  base_target_folder: /media/ola/324ac400-018f-4d6b-941e-361b54f3e5f6/targets
  data_folder: ${data.base_data_folder}/${data.type}/
  train_targets: ${data.base_target_folder}/train_data.csv
  val_targets: ${data.base_target_folder}/val_data.csv
  test_targets: ${data.base_target_folder}/test_data.csv

logging:
  logging_enabled: True
  project_name: 'eiphodos/SUEF'
  experiment_name: ${model.name}

performance:
  cuddn_auto_tuner: True
  parallel_mode: True
  half_precision: True
  anomaly_detection: False
  gradient_clipping: False
  gradient_clipping_max_norm: 32752

data_loader:
  batch_size_train: 16
  batch_size_eval: 16
  n_workers: 10
  custom_collate: False
  drop_last: True
  weighted_sampler: True

optimizer:
  learning_rate: 0.001
  weight_decay: 0.0001
  use_scheduler: True
  s_patience: 35
  s_factor: 0.1

training:
  epochs: 100
  checkpointing_enabled: True
  continue_training: False
  checkpoint_save_path: /home/ola/Projects/SUEF/saved_models/
  freeze_lower: False

evaluation:
  use_best_sample: True