defaults:
  - data_type: img
  - model: i3d_bert
  - model_type: ${defaults.1.model}_${defaults.0.data_type}
  - transforms: ${defaults.0.data_type}
  - augmentations: ${defaults.0.data_type}
  - data_set: 2c

data:
  file_sep: ;
  allowed_views: [2]
  base_target_folder: /home/ola/Projects/SUEF/data
  data_folder: ${data.base_data_folder}/${data.type}/
  train_targets: ${data.base_target_folder}/train_data.csv
  val_targets: ${data.base_target_folder}/val_data.csv
  test_targets: ${data.base_target_folder}/test_data.csv

logging:
  logging_enabled: True
  project_name: 'eiphodos/SUEF'
  experiment_name: ${model.name}

performance:
  cuddn_auto_tuner: True
  parallel_mode: True
  half_precision: True
  anomaly_detection: False
  gradient_clipping: False
  gradient_clipping_max_norm: 32752

data_loader:
  batch_size: 16
  n_workers: 10
  custom_collate: False
  drop_last: True
  weighted_sampler: True

optimizer:
  learning_rate: 0.0001
  weight_decay: 0.00001

training:
  epochs: 30
  use_scheduler: False
  sched_step_size: 10
  sched_gamma: 0.1
  checkpointing_enabled: True
  checkpoint_save_path: /home/ola/Projects/SUEF/saved_models/
  freeze_lower: False
