defaults:
  - model: i3d 
  - model_type: ${defaults.0.model}_${data.type}
  - transforms: ${data.type}
  - augmentations: ${data.type}
  - data_set: 2c

data:
  type: 2stream
  file_sep: ;
  base_data_folder: /media/ola/324ac400-018f-4d6b-941e-361b54f3e5f6
  base_target_folder: /home/ola/Projects/SUEF/data

logging:
  logging_enabled: True
  project_name: 'eiphodos/SUEF'
  experiment_name: 'i3d'

performance:
  cuddn_auto_tuner: True
  parallel_mode: True
  half_precision: True
  anomaly_detection: False
  gradient_clipping: True
  gradient_clipping_max_norm: 32752

data_loader:
  batch_size: 16
  n_workers: 10
  custom_collate: False
  drop_last: True
  shuffle: True

optimizer:
  learning_rate: 0.01
  weight_decay: 0.0001

training:
  epochs: 30
  use_scheduler: True
  sched_step_size: 10
  sched_gamma: 0.1
  checkpointing_enabled: True
  checkpoint_save_path: /home/ola/Projects/SUEF/saved_models/
  freeze_lower: False
