defaults:
  - data_stream: flow
  - model: i3d 
  - model_type: ${defaults.1.model}_${defaults.0.data_stream}
  - transforms: ${defaults.0.data_stream}
  - augmentations: ${defaults.0.data_stream}
  - data: base
  - data_set: test

logging:
  logging_enabled: False
  project_name: 'eiphodos/SUEF'
  experiment_name: 'i3d'

performance:
  cuddn_auto_tuner: True
  parallel_mode: True
  anomaly_detection: False
  gradient_clipping: False
  gradient_clipping_max_norm: 32752

data_loader:
  batch_size: 16
  n_workers: 11
  custom_collate: False
  drop_last: True
  shuffle: True

optimizer:
  learning_rate: 0.01
  weight_decay: 0.0001

training:
  epochs: 25
  use_scheduler: True
  sched_step_size: 10
  sched_gamma: 0.1
  checkpointing_enabled: True
  checkpoint_save_path: /home/ola/Projects/SUEF/saved_models/
  freeze_lower: False
